apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.letsencrypt.staging.name }}
  namespace: {{ .Release.Namespace }}
spec:
  acme:
    server: {{ .Values.letsencrypt.staging.server }}
    email: {{ .Values.letsencrypt.email }}
    privateKeySecretRef:
      name: {{ .Values.letsencrypt.staging.name }}
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.letsencrypt.production.name }}
  namespace: {{ .Release.Namespace }}
spec:
  acme:
    server: {{ .Values.letsencrypt.production.server }}
    email: {{ .Values.letsencrypt.email }}
    privateKeySecretRef:
      name: {{ .Values.letsencrypt.production.name }}
    solvers:
      - http01:
          ingress:
            class: nginx